apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: database
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-monitor
  namespace: database
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-monitor-binding
  namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-monitor
subjects:
- kind: ServiceAccount
  name: mongodb
  namespace: database
