kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  proxy-connect-timeout: "10"
  proxy-read-timeout: "3600"
  proxy-send-timeout: "3600"
