kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-persistent-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
