kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-persistent-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 25Gi
