apiVersion: v1
kind: Service
metadata:
  name: kube-dns-ext
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  type: NodePort
  selector:
    k8s-app: kube-dns
  ports:
  - name: dns
    port: 53
    nodePort: 12053
    protocol: UDP
  - name: dns-tcp
    port: 53
    nodePort: 12053
    protocol: TCP
