apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rbd-provisioner
  namespace: ceph
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-provisioner
    spec:
      containers:
      - name: rbd-provisioner
        # Currently outdated, hence use version from private registry
        # built from https://github.com/kubernetes-incubator/external-storage
        # (in ceph/rbd subdir)
        #image: "quay.io/external_storage/rbd-provisioner:latest"
        image: "registry.kbsg.rwth-aachen.de/timn/rbd-provisioner:latest"
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/rbd
      serviceAccount: rbd-provisioner
      imagePullSecrets:
      - name: regsecret

