#!/usr/bin/env python3

from job_generator import JobGenerator

import argparse

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='Create RCLL Cluster Sim Job')
	parser.add_argument('--team-cyan', metavar='NAME', required=True,
	                    help='Name of cyan team')
	parser.add_argument('--team-magenta', metavar='NAME', default="none",
	                    help='Name of magenta')
	parser.add_argument('--template', metavar='FILENAME', required=True,
	                    help='Template file for job parameters.')
	parser.add_argument('--debug', dest='debug', action='store_true',
	                    help='Template file for job parameters.')
	parser.add_argument('tournament_name', metavar="T-NAME",
	                    help='Tournament name (prefix for job names)')
	args = parser.parse_args()

	jobgen = JobGenerator(args.template, args.debug)
	(jobname, idnum, params) = \
	  jobgen.generate_and_store(args.tournament_name, args.team_cyan, args.team_magenta)

	print("Generated %s" % jobname)
