#!/usr/bin/env python3

from work_queue import WorkQueue
from config import Configuration

import argparse
from datetime import datetime, timedelta
from pprint import pprint

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='Print job info')
	parser.add_argument('--open', action='store_true',
	                    help='Show open jobs.')
	parser.add_argument('job_name', metavar="JOB-NAME", nargs='*',
	                    help='Name of job to retrieve info for.')
	args = parser.parse_args()

	config = Configuration()
	wq = WorkQueue(host=config.mongodb_host,
	               port=config.mongodb_port,
	               uri=config.mongodb_uri,
	               srv_name=config.mongodb_rs_srv,
	               database=config.mongodb_queue_db,
	               replicaset=config.mongodb_rs,
	               collection=config.mongodb_queue_col)

	if args.job_name:
		item =  wq.get_specific_item(args.job_name)
		if item is None:
			print("Failed to retrieve item with name '%s'" % args.job_name)
		else:
			pprint(item)

	if args.open:
		recently_failed_deadline = datetime.utcnow() - timedelta(minutes=15)
		(all_pending, without_recently_failed) = wq.num_pending_jobs(recently_failed_deadline)
		
		print("Open jobs: %d (additional recently failed: %d)" \
		      % (without_recently_failed, (all_pending-without_recently_failed)))

