apiVersion: v1
kind: Pod
metadata:
  name: rcll-sim-ctrl-dev
  labels:
    app: rcll-sim-ctrl-dev
  annotations:
    scheduler.alpha.kubernetes.io/tolerations: '[{"key":"exclusive", "operator":"Equal", "value":"rcll-sim"}]'
spec:
  containers:
    - name: rcll-sim-ctrl-dev
      image: registry.kbsg.rwth-aachen.de/timn/rcll-sim-ctrl:latest
      imagePullPolicy: Always
      command: ["bash"]
      args: ["-c", "chmod 700 /root/.ssh; /usr/libexec/openssh/sshd-keygen ecdsa && /usr/sbin/sshd -D"]
      env:
      - name: MONGODB_RS
        value: rs0
      - name: MONGODB_RS_SRV
        value: _mongodb._tcp.mongodb.database
      volumeMounts:
      - name: ssh-authkeys
        mountPath: /root/.ssh
  volumes:
  - name: ssh-authkeys
    configMap:
      name: ssh-authkeys-timn
      items:
      - key: authkeys
        path: authorized_keys
        mode: 0600
  imagePullSecrets:
    - name: regsecret
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rcll-sim-ctrl-dev
  name: rcll-sim-ctrl-dev
spec:
  type: NodePort
  ports:
  - port: 22
    nodePort: 12400
    #targetPort: 22
  selector:
    app: rcll-sim-ctrl-dev

